### PR TITLE
refactor: Vue components, tailwind/daisyui

### PR DESCRIPTION
**Pull request by twisttaan**
Preview: https://cdn.tristancamejo.com/e/simpmeter/p%3A1d%3A7-oct-22/index

### CODE REVIEW

**Review by castdrian — CHANGES_REQUESTED** [review]
it appears that is currently duplicates the results twice onto page resulting in triple results - ahh so many results

**Comment by twisttaan** [comment]
Strange, I can't replicate it.
cdn tristancamejo com_e_simpmeter_p%3A1d%3A7-oct-22_index

**Comment by twisttaan** [comment]
Though I do want to add some chip buttons to display the timelines instead of dumping them all on top of each other.

image

**Comment by castdrian** [comment]
> Strange, I can't replicate it.

Nevermind I'm just dumb an incapable of reading, I opened this on Android and due to the somewhat meh responsiveness Vue is providing it just looked like 3 times the same thing as it cut off the month/year/all-time

**Comment by castdrian** [comment]
> Though I do want to add some chip buttons to display the timelines instead of dumping them all on top of each other.
> 
> image
> 

Ideally what I plan on doing is to add dropdowns that influence the results or how many and what timeframe, defaulting to 10 results and 1 month, which is most likely what I'm gonna after I fix the CNAME issue

**Review by castdrian — APPROVED** [review]

**Pull request merged**
